### PR TITLE
ddp_ex_MF_7_6_4_jl

### PR DESCRIPTION
**Pull request by akihirosasaki**
julia translation ddp_ex_MF_7_6_4_py

### CODE REVIEW

**Review by oyamad — APPROVED** [review]

**Comment by sglyon** [comment]
Does this routine work with `a_indices` containing elements equal to `0`? I would think this would cause out of bounds indexing errors

**Comment by oyamad** [comment]
@sglyon Good point.

Now looking into the `ddp` code, `a_indices` is actually not used as action "indices" (apart from your newly added conversion routines in the Python version), but rather it can be used as action "values" (as long as they are sorted). (Apparently I wasn't really understanding the logic when I was writing the initial Python version...)

There are two alternatives:

1. Rename `a_indices` to `a_values`. For `to_product_form`, raise an error if not `np.array_equal(self.a_values, np.arange(self.a_values.max())`.
2. Leave `a_indices` as is, and (implicitly or explicitly) let the advanced user use it as action values.

(I would vote for alternative 2, as it involves no costs...)

**Comment by sglyon** [comment]
Hmm, are you certain that they aren't used as indices? From [these lines](https://github.com/QuantEcon/QuantEcon.jl/blob/f9a34ddcf2f97e3b989e05030ae5b7d13c395f25/src/markov/ddp.jl#L132-L133) it looks like the Julia version uses them as indices when constructing a sparse matrix

**Comment by oyamad** [comment]
You are right (and in [these lines](https://github.com/QuantEcon/QuantEcon.py/blob/ecbf2b291ef7d2df4a4460d76c1a625e63b2b55e/quantecon/markov/ddp.py#L338-L340) in the Python version). But these lines are not reached if `_has_sorted_sa_indices` is true (so the qualification "as long as they are sorted").

**Pull request merged**
