### PR TITLE
Add python/julia codes for solving NK Model in CLMM

### PR DESCRIPTION
**Pull request by sglyon**
In this PR I included two notebooks that serve as part of the appendix for a working paper I'm working on with @cc7768 and @maliars.

The notebooks provide code for solving a New Keynesian model with an option to impose or not impose a zero lower bound on interest rates.

Once the paper has a home somewhere online I will update these notebooks to include a link to the paper.

@cc7768  might have a couple more notebooks coming that are the other part of our Python/Julia appendix demonstrating 7 different algorithms for solving a standard growth model.

### CODE REVIEW

**Comment by thomassargent30** [comment]
This would be a very good addition

**Comment by cc7768** [comment]
These notebooks are excellent. There is lots of useful code, but seem a little sparse in terms of words. If these will be "stand alone" notebooks on the QE notebooks site, it might be helpful to provide a little more description of the model and solution. (I guess you could counter this suggestion by saying that the details are in the paper and can be found there).

**Comment by sglyon** [comment]
I was also a little torn about having np description  of the model, but after having thought about it I see it as more of an advantage. This is an online appendix and the paper contains the model.

If you think it would be better I would be happy to include the list of equilibrium conditions and variables (similar to what we do in the main body of the paper right now). Thoughts?

**Comment by jstac** [comment]
@sglyon Many thanks.  Very interesting.

In my view we could do without all the equations as long as we have a link to the paper embedded in the notebook.  Do you have a permanent URL?  

Also, at the end of the computations I was looking forward to seeing interpretation.  I suppose that's in the paper and if so that's fine --- there's no need to repeat.  But perhaps at the end of each notebook a line that says interpretation can be found in the paper would be good.

**Comment by sglyon** [comment]
Hey @jstac that's a good idea. I'll at least add a line directing people to the paper if they want to learn more and see some interpretation.

Once we hear  @cc7768's vote about the equations, we can make final decision about that.

We don't yet have a permanent URL, but when we do I'll revise these notebooks and put it in.

**Comment by cc7768** [comment]
I could live without the equations if we eventually can point to a place where people could investigate if they were interested in them.

I guess my opinion that it is sparse on words depends on whether this is meant solely as a computational appendix (i.e. a place for people to read and explore the code after having viewed the paper) or whether this is meant to be a standalone notebook people may stumble across on QE. My interpretation was that we would hope for interest generated in both directions, if that is true, I think the notebook could use a few more words. For example, in the "Solution Routine" section there are no words that describe what is happening. A couple words in the solution routine section and a "conclusion" paragraph would add some value (even though a lot of it would already be said in the paper).

**Pull request merged**
