### PR TITLE
FIX repeated game note

### PR DESCRIPTION
**Pull request by Yuya-Furusawa**
Fix recursive repeated game notebook.
Original note is based on old version of Julia(ver0.X?).
I fix the note to be compatible with ver 1.3.

### CODE REVIEW

**Comment by oyamad** [comment]
Great, thanks!
Can you briefly describe the major changes you made and the problems (regarding plots)?

**Comment by Yuya-Furusawa** [comment]
Major changes are:
- Change package dependencies
- Use appropriate functions instead of old functions(such as `linspace`)
- Fix some typos

There may be no problems in plotting graph(I will check later).  There are some issues in `Clp` package and I opened [the issue](https://github.com/JuliaOpt/Clp.jl/issues/73#event-3246437693), but it is resolved.

**Comment by oyamad** [comment]
As I see it, the plots are not displayed at `nbviewer`: https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/896acada3e648408d89e55c730efc7c959d35aa3/recursive_repeated_games.ipynb

**Comment by Yuya-Furusawa** [comment]
Oh,
There is no problem in my local environment, but the plots are not displayed properly once I pushed it to GitHub.
The message "Unable to load WebIO. Please make sure WebIO works for your Jupyter client. For troubleshooting, please see the WebIO/IJulia documentation." comes up.
I think this issue is due to my local environment and it is resolved by pushing from another environment.

**Comment by oyamad** [comment]
The same for me: Plots are displayed on my local computer, but not on `nbviewer`: https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/Yuya-Furusawa-rgnote/recursive_repeated_games.ipynb

Has this issue JuliaGizmos/WebIO.jl#381 been addressed?

@cc7768 Do you have any thought? Would it be possible to replace `PlotlyJS` with something else?

**Comment by amit1rrr** [comment]
Sorry to intrude but I noticed this PR contains Jupyter notebook files that are hard to review on GitHub due to the JSON diffs.

You might want to checkout [ReviewNB](https://www.reviewnb.com/), code review tool for notebooks. Provides visual diffs & commenting for Jupyter notebooks on GitHub. Completely free for open source repositories.

Disclaimer: I built ReviewNB

diff_and_commenting

**Pull request closed without merging**
