### PR TITLE
Adding translation into Julia of the Wald Friedman Python notebook

### PR DESCRIPTION
**Pull request by albep**
This PR translates into Julia the Python notebook https://github.com/albep/QuantEcon.notebooks/blob/master/Wald_Friedman.ipynb, with some small changes to the text in order ensure consistency with the absence of sliders and the use of Julia types and methods

### CODE REVIEW

**Comment by cc7768** [comment]
Some comments:

 * Typically in Julia docstrings go before a function definition instead of after -- See this [example](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/interp.jl)
* Since everything here is 1-D, it might be more readable if you use the 1-D interpolation that we have in `QuantEcon.jl`. See [here](https://github.com/jstac/QuantEcon.lectures/issues/211#issuecomment-289535289) and [here](https://github.com/QuantEcon/QuantEcon.jl/issues/152)

Otherwise I think this looks really nice. @thomassargent30, do you have any comments?

**Comment by albep** [comment]
@cc7768 thanks for the comments. I addressed both of them in the latest commit

**Comment by cc7768** [comment]
Perfect. I think this looks ready to go. @jstac, I think this is ready to merge. I would let it sit for the rest of the day to see if anyone else has comments, but otherwise I think it is ready.

**Comment by jstac** [comment]
Thanks all.  This is very nice.  Merging.

**Pull request merged**
