### PR TITLE
Pandas graphics

### PR DESCRIPTION
**Pull request by jstac**
This PR adds Dave's notebook on graphics and pandas

### CODE REVIEW

**Comment by cc7768** [comment]
@spencerlyon2 made a comment somewhere (may have been email), but this notebook needs to be updated to access the `DataReader` in the new way. The way it is being used right now is deprecated.

See the warning in notebook:

```
C:\Users\dbackus\Anaconda3\lib\site-packages\pandas\io\data.py:33: FutureWarning: 
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)
```

**Comment by mmcky** [comment]
This is a bit of a tricky one - as the website for `pandas_datareader` says: 

```
In future pandas releases (0.17+) pandas-datareader will become a dependancy and using pandas.io.data will be equivalent to using pandas_datareader.data.
```

It looks like it will work from the pandas package once this dependency is setup. As of `0.17.1` this doesn't work yet though. Also as far as I know the current `pandas_datareader` package is not included in `anaconda` at the moment and will require a `pip install pandas_datareader`. 

I propose to update this to use the pandas_datareader package and open an issue to adjust this notebook back to using `pandas.io.data` once working again in `pandas.io`.

**Comment by mmcky** [comment]
This line is going to cause issues with the testing scripts if there is no `../Temp/` folder. 
Is it ok to update this so the file is saved in the current working directory?

**Comment by mmcky** [comment]
This is now ready to merged and added to `QuantEcon.site` notebook gallery

**Pull request merged**
