### PR TITLE
Adding discrete dp julia notebooks that need review prior to merge

### PR DESCRIPTION
**Pull request by mmcky**
The following notebooks need a Julian review. 
- ddp_theory_jl.ipynb [Help needed]
  I don't know how to set the column names and the row indices of the DataFrame table.
  - ddp_ex_job_search_jl.ipynb [Review needed]
    Very slow. Maybe type declarations are not appropriate?

### CODE REVIEW

**Comment by ZacCranko** [comment]
`ddp_ex_job_search_jl.ipynb` looks fine to me (n.b. @mmcky, in the original post 'Very slow.' is a strikethrough) Performance is fine. Type declarations also seem fine to me too.

**Comment by oyamad** [comment]
@ZacCranko Thanks!

A few days ago I learned about `@code_warntype` in a hands-on tutorial on performance tuning in a "Julia Tokyo" meeting (where I gave a short talk on `DiscreteDP` with the job search example). I am now going to apply the tips introduced there to seek for (possibly marginal) performance gains.

**Comment by ZacCranko** [comment]
`ddp_theory_jl.ipynb` Just had a look at this one. @oyamad I think the most convenient method for constructing data frames for your example would be like this 

``` julia
using DataFrames

i = rand(1:20, 20)
f = randn(20)
s = rand(["meow", "woof", "bang"], 20)

columns = Any[i,f,s]

# first example
names = [:ints, :floats, :sounds]
DataFrame(columns, names) |> show

# second example
fancy_names = [symbol("some ints"), symbol("some floats"), symbol("and some sounds")]
DataFrame(columns, fancy_names) |> show
```

The second example is the easiest method I found if you want spaces in your column titles. You can probably automate this with something like `map(symbol, names::Vector{AbstractString})` if you have a vector of `AbstractString`s. Note also that the `DataFrame(columns::Vector{Any}, names::Vector{Symbol})` constructor is really picky about types. 

The documentation for `DataFrames.jl` is a bit... sparse. I found this out by looking at [dataframe.jl](https://github.com/JuliaStats/DataFrames.jl/blob/master/src/dataframe/dataframe.jl). 

Is there anything else I can help you with?

**Comment by oyamad** [comment]
@ZacCranko Great, thanks. I will try that.

Basically, I want to reproduce the tables in cells 12 and 13 in [ddp_theory_py](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/ddp_theory_py.ipynb) into cells 12 and 13 in [ddp_theory_jl](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp-julia/ddp_theory_jl.ipynb).

**Comment by ZacCranko** [comment]
@oyamad Let me figure this out. I think there might be some cool stuff we can do with LaTeX strings...

**Comment by ZacCranko** [comment]
From the looks of how the `DataFrames.jl` folks have defined `show` we won't be able to print a nice pretty set of LaTeX column headers like the Python implementation since column names in `DataFrames.jl` _must_ be italics. Alternately we could use unicode `_names = map(symbol, ["vⁱ(0)", "vⁱ(1)", "‖v^i - v^(i-1)‖"])`.

**Comment by oyamad** [comment]
@ZacCranko Thanks for the research.

I would also like to do an operation equivalent to setting `df.index` as in Pandas (see also `In [38]: df.index = countries` in [this page](http://quant-econ.net/py/pandas.html#dataframes)), but it seems Julian `DataFrame` doesn't have any such operation (or doesn't even have a concept of row names?).

**Comment by oyamad** [comment]
I revised `ddp_theory_jl.ipynb` according to the solution by @ZacCranko.

I wanted not to print the numbers in the left most column which are totally useless, but I gave up. Anyway important information is there in the tables. Thank you for your help @ZacCranko.

**Comment by oyamad** [comment]
I revised `ddp_ex_job_search_jl.ipynb`, where
- I changed `Real` to `Float64`,
- added type annotations, in order for `ANY` not to show up in `@code_warntype`, and
- pulled `budget_balance` out of a function.

The speed slightly improved (about 10%?), but it can be just noise.

If @ZacCranko and @spencerlyon2 think it OK, this PR can be merged.

**Comment by mmcky** [comment]
Thanks @oyamad and @ZacCranko for these updates. This looks good to go. @ZacCranko and @spencerlyon2 I will await your response prior to merge.

**Comment by sglyon** [comment]
You can merge away. 

I haven't taken a very close look, but I trust @oyamad  -- his bar for quality standards is very high!

**Pull request merged**
