### PR TITLE
Notebooks on DiscreteDP

### PR DESCRIPTION
**Pull request by oyamad**
Notebooks on `DiscreteDP`:
1. Getting started
   - [ddp_intro_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_intro_py.ipynb)
2. Implementation details
   - [ddp_theory_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_theory_py.ipynb)
   - [ddp_theory_jl.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_theory_jl.ipynb) [Help needed]  
     I don't know how to set the column names and the row indices of the `DataFrame` table.
3. Automobile replacement
   - [ddp_ex_rust96_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_rust96_py.ipynb)
4. Optimal growth
   Just wrapping the procedures in the [solutions notebook](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.applications/blob/master/discrete_dp/discrete_dp_solutions_py.ipynb) into a class.
   - [ddp_ex_optgrowth_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_optgrowth_py.ipynb)
5. Job search
   Alternative implementation for the [lecture on job search](http://quant-econ.net/py/lake_model.html#endogenous-job-finding-rate) using `DiscreteDP`.
   - [ddp_ex_job_search_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_job_search_py.ipynb)
   - [ddp_ex_job_search_jl.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_job_search_jl.ipynb) [Review needed]  
     ~~Very slow.~~ Maybe type declarations are not appropriate?
   
   ~~Some issues: see QuantEcon/QuantEcon.applications#14.~~ (Resolved)
6. Career choice
   Alternative implementation for the [lecture on career choice](http://quant-econ.net/py/career.html) using `DiscreteDP`.
   - [ddp_ex_career_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_career_py.ipynb)
7. Examples from Miranda and Fackler
   - [ddp_ex_MF_7_6_2_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_MF_7_6_2_py.ipynb)
   - [ddp_ex_MF_7_6_3_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_MF_7_6_3_py.ipynb)
   - [ddp_ex_MF_7_6_4_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_MF_7_6_4_py.ipynb)  
     One of the figures looks different from the original one; see https://github.com/QuantEcon/QuantEcon.py/issues/185#issuecomment-153020375.
   - [ddp_ex_MF_7_6_5_py.ipynb](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_MF_7_6_5_py.ipynb)

Please feel free to edit any of the notebooks.

### CODE REVIEW

**Comment by jstac** [comment]
@spencerlyon2 @zaccranko Is there any chance either of you could help @oyamad get the two problematic Julia notebooks (see comments above) fixed up?

**Comment by mmcky** [comment]
@jstac Would you be happy to merge these excellent notebooks into master and then add an issue to track the two problematic Julia notebooks fixed up. (Or we could pull those two notebooks out in a separate PR - so that they aren't sitting on master?)

**Comment by jstac** [comment]
@mmcky Good idea. I would be happy to merge them into master and put issues in the issue tracker.    When we build the front page for the notebooks we can omit the problematic ones from the list until the issues are resolved.

**Comment by oyamad** [comment]
In `ddp_ex_job_search_jl.ipynb`, I set the tolerance to some not so small value for `fzero` from `Roots.jl` (in cell `[9]`). I think the speed is acceptable now.

Review is still appreciated.

**Comment by ZacCranko** [comment]
@jstac Sorry, just caught this message today. Yep, happy to help out. I'll take a look at `ddp_theory_jl.ipynb` tomorrow.

**Comment by mmcky** [comment]
All - I am merging this branch to get the majority of notebooks on master. 

Then I will pull out the following notebooks into a separate PR to track their updates. 

ddp_theory_jl.ipynb [Help needed]
I don't know how to set the column names and the row indices of the DataFrame table.

ddp_ex_job_search_jl.ipynb [Review needed]
Very slow. Maybe type declarations are not appropriate?

**Comment by oyamad** [comment]
@mmcky Thanks!

Deleted the branch `mdp` in `QuantEcon.site`.

**Comment by sglyon** [comment]
@ZacCranko @oyamad do we still need someone to take a look at these 2 notebooks?

I just finished a big chunk of what I planned on finishing before Christmas and might have some time to do some review tomorrow.

**Comment by ZacCranko** [comment]
@spencerlyon2 see the discussion [here](https://github.com/QuantEcon/QuantEcon.notebooks/pull/12).

**Pull request merged**
