### PR TITLE
Added Ransom notebooks

### PR DESCRIPTION
**Pull request by tyleransom**
I've added the following 3 Jupyter notebooks:
- dataframes_examples.ipynb
- regression_models.ipynb
- jump_optimization.ipynb

I've also added a CSV file to the dependencies folder, which is required to run some of the notebooks.

### CODE REVIEW

**Comment by jstac** [comment]
@tyleransom Just minor comments:

Did you want to add your email address or a link to your GitHub repo to the top of the notebooks?  It's up to you, of course.

Also, in cell [2] of `jump_optimization` (and perhaps elsewhere) you've used tabs instead of spaces. The style guide recommends spaces:

https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md
"4 spaces per indentation level, no tabs"

**Comment by tyleransom** [comment]
@jstac Thanks for pointing those out. I've updated the notebooks to include my email address, GitHub repo link, and changed indentations from tabs to 4 spaces.

**Comment by jstac** [comment]
@tyleransom Thanks, they look good.  

@mmcky Would you mind to give these a very quick eyeball (I've already looked them over) and then merge if you're happy?

**Comment by jstac** [comment]
@mmcky Just a reminder to merge these when you have a moment.  They look pretty good to me.

@tyleransom Sorry for the delay -- it's been a busy week.

**Comment by mmcky** [comment]
@tyleransom Sorry for holding things up. These notebooks look great. I notice the dependency file `auto.csv` isn't setup to download from the dependency folder on GitHub. We have a simple fetch utility on the `Python` side but this is not yet implemented on the Julia side. I think this is fine as you have documented how to get the data file well. 

@jstac Merging this and I will push a PR for the gallery.

**Comment by tyleransom** [comment]
@jstac @mmcky Thanks!

**Pull request merged**
